### ISSUE TITLE
Date format Transaction

### ISSUE THREAD

**Issue by Vruizvil** [oopsmonk/iota_esp32_wallet#12] opened 2019-10-21 15:49 UTC
Hi. The transactiones from esp32 wallet, show an strange date format on trinity.
![error-date-format](https://user-images.githubusercontent.com/20659831/67221011-108da480-f42b-11e9-8f52-448b17b6f315.jpg)

**Comment by oopsmonk** [comment] 2019-10-22 02:27
thanks for your report @Vruizvil, it's caused by https://github.com/iotaledger/entangled/issues/1449

**Comment by oopsmonk** [comment] 2019-10-22 09:33
@Vruizvil Can you confirm it's fixed in f03fbf66b585ac8b571874a18eb7c6c6bf0ce768? thanks.

**Closed as completed** 2020-06-15 03:11 UTC
